service: alexa-service
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - 'lambda:InvokeFunction'
       Resource: '*'

custom:
  chaosServiceName: chaos-service
  chaosServiceLambdaPrefix: ${self:custom.chaosService}-${opt:stage}
package:
  exclude:
    - .git/**
    - node_modules/**
    - test/**
    - '*'
    - 'src/.node_version'
    - 'src/package.json'
    - 'src/yarn.lock'
  include:
    - 'src/**'

functions:
  alexa:
    handler: src/alexa.handler
    environment:
      ALEXA_APPLICATION_ID: amzn1.ask.skill.69483f2c-0154-4cf1-a9d9-f7b697c65a54
      COUNT_LAMBDA: ${chaosServiceLambdaPrefix}-instanceCount
      TERMINATE_LAMBDA: ${chaosServiceLambdaPrefix}-instanceTerminate
      STOP_LAMBDA: ${chaosServiceLambdaPrefix}-instanceStop

#resources:
#  Resources:
#  Outputs:
