service: alexa-service
provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - 'lambda:InvokeFunction'
       Resource: '*'

custom:
  chaosService:
    name: chaos-service
    lambdaPrefix: ${self:custom.chaosService.name}-${opt:stage}
package:
  exclude:
    - .git/**
    - coverage/**
    - node_modules/**
    - test/**
    - "*"
    - src/.node_version
    - src/package.json
    - src/yarn.lock
  include:
    - src/**

functions:
  alexa:
    handler: src/alexa.handler
    environment:
      ALEXA_APPLICATION_ID: ${env:ALEXA_APPLICATION_ID}
      COUNT_LAMBDA: ${self:custom.chaosService.lambdaPrefix}-instanceCount
      START_LAMBDA: ${self:custom.chaosService.lambdaPrefix}-instanceStart
      TERMINATE_LAMBDA: ${self:custom.chaosService.lambdaPrefix}-instanceTerminate
      STOP_LAMBDA: ${self:custom.chaosService.lambdaPrefix}-instanceStop

#resources:
#  Resources:
#  Outputs:
